"""The whole sub-app roster this library ships, built over one declaration.

A project used to name its inherited sub-apps one by one, which put the roster
on the wrong side of the boundary between the two halves of lup. The library
arrives through a lock refresh and the template through a hand-replayed commit,
so a sub-app added here reached a project's dependencies immediately and its
``--help`` never: the name was written down in a copied file nobody had reason
to revisit, and an absent sub-app read exactly like a declined one.

So the default is everything, and a project states its delta. What made that
possible is that the factories need only the handful of facts
:class:`DevtoolsDeclarations` carries, every one of which a project already
declares once for something else — which also retires the other half of the
drift, because a factory that grows an argument grows a field there with a
default rather than breaking a call site in every downstream at once.

One table, two renderings. Prose about the CLI is generated into the harness
and the harness is generated by the CLI, so a document naming the roster must
reach it without constructing a Typer app; :data:`LIBRARY_SPECS` is that
reading and :meth:`DevtoolsDeclarations.roster` the other. Both project the
same entries, so a roster the documents describe and a roster the CLI serves
cannot disagree.
"""

from collections.abc import Callable
from pathlib import Path

import typer
from pydantic import BaseModel

from lup.devtools.dev.app import DevDeclarations, create_dev_app
from lup.devtools.feedback.app import create_feedback_app
from lup.devtools.feedback.models import AgentPrompt
from lup.devtools.harness.app import create_harness_app
from lup.devtools.harness.composition import NativeTargets
from lup.devtools.harness.drift import RepositoryWriter
from lup.devtools.harness.launch import LaunchCheckpoint, LaunchMode
from lup.devtools.harness.resolve import ConfiguredModel
from lup.devtools.hooks.app import create_hooks_app
from lup.devtools.report.app import create_report_app
from lup.devtools.setup import Integration, create_setup_app
from lup.devtools.subapps import SubApp, SubAppSpec
from lup.providers.profiles import ProfileDirectory
from lup.observability.usage.app import UsageEntry, create_usage_app

import lup.devtools.py.app as py
import lup.devtools.sync as sync
import lup.devtools.trace.app as trace
import lup.devtools.version as version


class DevtoolsDeclarations(BaseModel, frozen=True, arbitrary_types_allowed=True):
    """Everything the sub-apps this library ships need from one repository.

    Each field is a fact only the project has, and every one of them it already
    holds for another reason — so composing the roster asks for nothing new,
    which is what lets the roster itself stop being the project's to write.
    """

    dev: Callable[[], DevDeclarations]
    """What the dev tree reads about this repository, when a command runs."""

    targets: NativeTargets
    """Every native runtime this project generates a tree for."""

    repository_writers: list[RepositoryWriter]
    """Generated files that belong to no single native tree."""

    prompt: Callable[[], AgentPrompt]
    """This project's system prompt, as the health report weighs it."""

    relocate_roots: list[Path] = [Path("src"), Path("tests")]
    """Where `dev relocate` may move a module, for a project laid out that way."""

    integrations: list[Integration] = []
    """External services the setup wizard and dashboard walk an operator through."""

    usage_entries: list[UsageEntry] = []
    """One entry per backend whose account this project reads usage from.

    A project naming none retires ``usage`` rather than declaring an empty
    list into a served command tree, so a display over zero accounts is a
    decision `dev check` can name instead of an emptiness a reader discovers."""

    model: ConfiguredModel | None = None
    """The model a launch selects when the caller names none."""

    profiles: ProfileDirectory | None = None
    """The accounts this project keeps, where it keeps its own."""

    launch_modes: list[LaunchMode] = []
    """Named ways of opening a session that this project's default is not.

    Empty for a project whose sessions are all the same kind. One entry adds
    a flag to every launcher, compiles the tree that mode declares while it is
    in force, and opens whatever that kind of session needs around the run."""

    launch_checkpoint: LaunchCheckpoint | None = None
    """Application data saved before generation and after the native CLI closes."""

    def roster(self, retired: list[str] | None = None) -> list[SubApp]:
        """Every sub-app the library ships, wired over these declarations.

        ``retired`` is what a project has declined, and an entry named there is
        *not built* rather than built and dropped afterwards. That distinction
        is the whole reason this takes an argument: a builder may import an
        optional extra, so constructing an app a project declined makes that
        project carry a dependency for a command it does not serve. Measured —
        a project retiring ``dashboard`` still could not start its CLI without
        ``lup[web]``, because the roster built the dashboard before the
        selection ever saw it.

        Defaulting to none keeps every existing caller correct: a project that
        declines nothing gets exactly what it got before.
        """
        declined = retired or []
        return [
            entry.wired(self)
            for entry in LIBRARY_ROSTER
            if entry.spec.name not in declined
        ]


class RosterEntry(BaseModel, frozen=True, arbitrary_types_allowed=True):
    """One sub-app the library ships: what it is called, and how it is built.

    The pair is what makes the two readings one table. A roster listed for a
    document and a roster wired into a CLI are the same entries seen through
    different halves of this model, so neither can name a sub-app the other
    does not.
    """

    spec: SubAppSpec
    build: Callable[[DevtoolsDeclarations], typer.Typer]

    def wired(self, declared: DevtoolsDeclarations) -> SubApp:
        """This entry as a composable sub-app, over one project's declaration."""
        return SubApp(spec=self.spec, app=self.build(declared))


def conversation_app(declared: "DevtoolsDeclarations") -> typer.Typer:
    """The conversation sub-app, imported where it is built.

    Deferred because retaining a hosted transcript drives a real browser,
    which is the ``conversation`` extra. A module-level import makes that extra
    a requirement of importing this file at all — so a project that declines
    the sub-app still could not start its CLI without it.
    """
    from lup.devtools.conversation.app import create_conversation_app

    return create_conversation_app(declared.profiles)


def dashboard_app(declared: "DevtoolsDeclarations") -> typer.Typer:
    """The dashboard sub-app, imported where it is built.

    Deferred for the same reason as :func:`conversation_app`: it serves the
    setup wizard over HTTP, which is the ``web`` extra.
    """
    from lup.devtools.dashboard.app import create_dashboard_app

    return create_dashboard_app(declared.integrations)


# lup: ignore[library-default] — the sub-apps this library authors, so the table
# is what it ships rather than a choice made for an adopter
LIBRARY_ROSTER = [
    RosterEntry(
        spec=SubAppSpec(
            name="conversation", help="Retain authenticated AI conversations"
        ),
        build=lambda declared: conversation_app(declared),
    ),
    RosterEntry(
        spec=SubAppSpec(name="dashboard", help="Host the local setup dashboard"),
        build=lambda declared: dashboard_app(declared),
    ),
    RosterEntry(
        spec=SubAppSpec(name="dev", help="Worktrees, branches, and pre-flight checks"),
        build=lambda declared: create_dev_app(
            declared=declared.dev,
            native_targets=declared.targets,
            repository_writers=declared.repository_writers,
            relocate_roots=declared.relocate_roots,
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(name="feedback", help="Feedback state, metrics, and commits"),
        build=lambda declared: create_feedback_app(declared.prompt),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="harness", help="Generate and launch the native harnesses"
        ),
        build=lambda declared: create_harness_app(
            declared.targets,
            declared.repository_writers,
            declared.model,
            declared.profiles,
            declared.launch_modes,
            declared.launch_checkpoint,
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(name="hooks", help="Query the permission policy"),
        build=lambda declared: create_hooks_app(lambda: declared.dev().hooks),
    ),
    RosterEntry(spec=py.SUBAPP.spec, build=lambda _: py.SUBAPP.app),
    RosterEntry(
        spec=SubAppSpec(
            name="report", help="Everything left to implement, in one place"
        ),
        build=lambda declared: create_report_app(
            declared.targets, declared.repository_writers
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(name="setup", help="Interactive setup wizard"),
        build=lambda declared: create_setup_app(
            declared.integrations, declared.profiles
        ),
    ),
    RosterEntry(spec=sync.SUBAPP.spec, build=lambda _: sync.SUBAPP.app),
    RosterEntry(spec=trace.SUBAPP.spec, build=lambda _: trace.SUBAPP.app),
    RosterEntry(
        spec=SubAppSpec(name="usage", help="Runtime usage display"),
        build=lambda declared: create_usage_app(declared.usage_entries),
    ),
    RosterEntry(spec=version.SUBAPP.spec, build=lambda _: version.SUBAPP.app),
]
"""Every sub-app lup ships, in the order `--help` lists them."""

LIBRARY_SPECS = [entry.spec for entry in LIBRARY_ROSTER]
"""The roster as a document names it, reachable without constructing an app.

The other reading is :meth:`DevtoolsDeclarations.roster`, which projects the
same table into wired sub-apps. Both are this list of entries seen through one
half of :class:`RosterEntry`, so neither can name a sub-app the other does not.
"""
