"""How a sub-app says what it is, and how a CLI is composed from several.

The library ships no roster. Each sub-app module declares its own ``SUBAPP``
beside the Typer app it names, and the application that wants it says so —
which is the same inversion the rest of the library takes: nothing here
decides what an adopter runs, it decides what an adopter can compose.

That also settles where the name and help text live. A table listing every
sub-app is a second place they could be written, and the only way to read it
is to import every command module the entries point at — which makes the
roster unreadable from inside anything those modules import. A declaration
beside its own app has neither problem.
"""

import typer
from pydantic import BaseModel


class SubAppSpec(BaseModel, frozen=True):
    """What a sub-app is called and what it is for.

    Separate from the app it names because prose about the CLI is generated
    into the harness, and the harness is generated by the CLI: a document
    that imported the wired apps to learn their names would close that loop.
    A spec carries everything a reader needs and nothing that executes.
    """

    name: str
    help: str


class SubApp(BaseModel, frozen=True, arbitrary_types_allowed=True):
    """One sub-app: what it is called, and the Typer app that answers to it."""

    spec: SubAppSpec
    app: typer.Typer


def subapp(name: str, help: str, app: typer.Typer) -> SubApp:
    """Declare one sub-app without spelling its spec separately."""
    return SubApp(spec=SubAppSpec(name=name, help=help), app=app)


def resolved(subapps: list[SubApp]) -> list[SubApp]:
    """The roster with each name's last declaration winning, in first order.

    Position is where a name first appears and the definition is whichever
    entry declared it last, so an application replacing a sub-app it needs to
    differ on keeps the order a reader of ``--help`` already learned.
    """
    order = list(dict.fromkeys(entry.spec.name for entry in subapps))
    latest = {entry.spec.name: entry for entry in subapps}
    return [latest[name] for name in order]


def compose(root: typer.Typer, subapps: list[SubApp]) -> None:
    """Wire every resolved sub-app into one root Typer application."""
    for entry in resolved(subapps):
        root.add_typer(entry.app, name=entry.spec.name, help=entry.spec.help)


def subapp_summary(specs: list[SubAppSpec]) -> str:
    """Format the roster as an inline backticked name list."""
    return ", ".join(f"`{spec.name}`" for spec in specs)


def subapp_bullets(specs: list[SubAppSpec], indent: str = "") -> str:
    """Format the roster as Markdown bullet lines with help text."""
    return "".join(f"{indent}- `{spec.name}` — {spec.help}\n" for spec in specs)
