"""How a sub-app says what it is, and how a CLI is composed from several.

The library ships no roster. Each sub-app module declares its own ``SUBAPP``
beside the Typer app it names, and the application that wants it says so —
which is the same inversion the rest of the library takes: nothing here
decides what an adopter runs, it decides what an adopter can compose.

That also settles where the name and help text live. A table listing every
sub-app is a second place they could be written, and the only way to read it
is to import every command module the entries point at — which makes the
roster unreadable from inside anything those modules import. A declaration
beside its own app has neither problem.
"""

import typer
from pydantic import BaseModel


class SubAppSpec(BaseModel, frozen=True):
    """What a sub-app is called and what it is for.

    Separate from the app it names because prose about the CLI is generated
    into the harness, and the harness is generated by the CLI: a document
    that imported the wired apps to learn their names would close that loop.
    A spec carries everything a reader needs and nothing that executes.
    """

    name: str
    help: str


class SubApp(BaseModel, frozen=True, arbitrary_types_allowed=True):
    """One sub-app: what it is called, and the Typer app that answers to it."""

    spec: SubAppSpec
    app: typer.Typer


def subapp(name: str, help: str, app: typer.Typer) -> SubApp:
    """Declare one sub-app without spelling its spec separately."""
    return SubApp(spec=SubAppSpec(name=name, help=help), app=app)


def resolved(subapps: list[SubApp]) -> list[SubApp]:
    """The roster with each name's last declaration winning, in first order.

    Position is where a name first appears and the definition is whichever
    entry declared it last, so an application replacing a sub-app it needs to
    differ on keeps the order a reader of ``--help`` already learned.
    """
    order = list(dict.fromkeys(entry.spec.name for entry in subapps))
    latest = {entry.spec.name: entry for entry in subapps}
    return [latest[name] for name in order]


class SubAppSelection(BaseModel, frozen=True):
    """Which of the sub-apps this library ships a project's CLI serves.

    Subtractive for the reason ``RuleSelection`` is: a project wanting all but
    two should name those two rather than restate the rest, because a restated
    roster has to be re-copied every time the library adds a sub-app — and the
    copy that fell behind is indistinguishable from a decision. A project
    reading its own inherited list cannot tell a sub-app it declined from one
    that arrived after it copied the file, which is how a CLI comes to be
    missing a command tree nobody chose to be missing.

    Both renderings of a roster take the same selection. Prose about the CLI is
    generated into the harness and the harness is generated by the CLI, so the
    documents describe :class:`SubAppSpec` values that construct nothing while
    the CLI composes the apps — and one selection over both is what keeps a
    retired sub-app from being documented as served.
    """

    retired: list[str] = []
    """Sub-app names this project's CLI does not serve."""

    def over(self, defaults: list[SubApp], added: list[SubApp]) -> list[SubApp]:
        """This project's roster: the defaults it kept, and its own.

        An added entry naming a default replaces it — :func:`resolved` gives
        last-declaration-wins — so a project keeping its own `trace` says so by
        declaring one rather than by retiring and re-adding the name.

        Sorted by name because the result is a ``--help`` listing and that is
        the order a reader scans, where :func:`resolved` preserves declaration
        order for a caller composing one by hand.
        """
        kept = [entry for entry in defaults if entry.spec.name not in self.retired]
        return sorted(resolved([*kept, *added]), key=lambda entry: entry.spec.name)

    def specs(
        self, defaults: list[SubAppSpec], added: list[SubAppSpec]
    ) -> list[SubAppSpec]:
        """The same roster as the documents name it, constructing no app."""
        kept = [spec for spec in defaults if spec.name not in self.retired]
        latest = {spec.name: spec for spec in [*kept, *added]}
        return sorted(latest.values(), key=lambda spec: spec.name)


def compose(root: typer.Typer, subapps: list[SubApp]) -> None:
    """Wire every resolved sub-app into one root Typer application."""
    for entry in resolved(subapps):
        root.add_typer(entry.app, name=entry.spec.name, help=entry.spec.help)


def subapp_summary(specs: list[SubAppSpec]) -> str:
    """Format the roster as an inline backticked name list."""
    return ", ".join(f"`{spec.name}`" for spec in specs)


def subapp_bullets(specs: list[SubAppSpec], indent: str = "") -> str:
    """Format the roster as Markdown bullet lines with help text."""
    return "".join(f"{indent}- `{spec.name}` — {spec.help}\n" for spec in specs)
