# lup: ignore[constant-declaration]
# The application roster here is this project's own composition — the sub-apps
# only it has, and what each is called. A composition root is where a judgement
# is finally made rather than passed on, so there is no caller above it.
"""This application's sub-app delta: what it declines, and what only it has.

The library ships the whole roster and a project states the difference, rather
than restating the list. That inversion is the point: the two halves of lup
reach a project by different routes — the library through a lock refresh, this
file through a hand-replayed commit — so a roster enumerated here would go on
naming what lup shipped the day it was copied, and the sub-app that arrived
afterwards would be missing without anyone having decided it should be.

**What is declined is not written down here either.** A sub-app is one surface
of a subject, and a subject is a module: ``feedback`` is served because this
project took the feedback loop, and stops being served the moment it does not.
So the retirement is derived from the adopted roster, and a project changes
which commands it has by changing which modules it has.

Only specs here, never Typer apps. Documents under ``harness/content/``
describe this CLI and are themselves generated by it, so a roster that reached
for the wired apps to learn their names would make the guidance depend on the
tooling that renders it. ``devtools/main.py`` is where each name meets the app
that answers to it, and nothing imports ``main``.
"""

from lup.devtools.subapps import SubAppSpec

APPLICATION_ROSTER = [
    SubAppSpec(name="agent", help="Agent introspection and debugging"),
]
"""Every sub-app only this application has, whether or not it serves them.

The help text is here because a name is not a description and a module spec
carries only the name. Which of these the CLI actually serves is derived
beside the module roster, in ``harness/content/catalog.py``, where the rest of
what follows from a module selection is derived — this file is the one thing
that cannot be: what a sub-app of this project's own is *called*.
"""
