"""Generate the checked-in Lup rule reference from the canonical rule registry."""

import html
from pathlib import Path

from lup.codescan.registry import RegisteredRule, all_rules
from lup.workspace.paths import project_root


def markdown_cell(value: str) -> str:
    """Escape generated text for one Markdown table cell."""
    return html.escape(value).translate(str.maketrans({"|": "&#124;", "\n": " "}))


def render_rule_reference() -> str:
    """Render every executable Lup rule and typed-suppression convention."""
    rules = all_rules()
    structural = sorted(
        (rule for rule in rules if rule.family != "anti-pattern"),
        key=lambda item: item.id,
    )
    anti_patterns = sorted(
        (rule for rule in rules if rule.family == "anti-pattern"),
        key=lambda item: (item.scope, item.id),
    )

    def table(rows: list[RegisteredRule]) -> str:
        lines = [
            "| Rule id | Family | Scope | Matching example | Diagnostic | Defined in |",
            "|---|---|---|---|---|---|",
            *[
                "| "
                f"`{row.id}` | {row.family} | {markdown_cell(row.scope)} | "
                f"<code>{markdown_cell(row.example)}</code> | "
                f"{markdown_cell(row.message)} | `{row.defined_in}` |"
                for row in rows
            ],
        ]
        return "\n".join(lines)

    return (
        "# Lup rule reference\n\n"
        "<!-- Generated by `uv run lup-devtools dev rules`; do not edit by hand. -->\n\n"
        "Every executable Lup rule family — anti-pattern, boundary, spelling, and "
        "architecture rules — is indexed here from `lup.codescan.registry`, with the "
        "module that defines and enforces each rule. An edit-hook denial cites its "
        "rule id and this reference. Lup rules enforce repository-specific "
        "architecture and editing conventions; Ruff remains the source of standard "
        "Python diagnostics. The matching examples for anti-patterns are their "
        "canonical regular-expression shapes, so this reference cannot drift from "
        "the edit hook or repository auditor.\n\n"
        "## Typed suppressions\n\n"
        "Suppress one deliberate site with `# lup: ignore[rule-id]` and a reason. "
        "Comma-separated ids cover a line that intentionally matches several rules. "
        "A typed directive in the first ten lines applies file-wide. Bare "
        "`# lup: ignore` remains parseable but is reported as untyped; a stale typed "
        "directive is blocking. `# noqa`, `# type: ignore`, and `# pyright: ignore` "
        "are separate forbidden shapes.\n\n"
        "```python\n"
        "cache: dict[str, int] = {}  # lup: ignore[empty-collection] — mutable fold\n"
        "```\n\n"
        "## Structural rules\n\n"
        f"{table(structural)}\n\n"
        "## Edit anti-patterns\n\n"
        f"{table(anti_patterns)}\n"
    )


def write_rule_reference(path: Path | None = None, *, check: bool = False) -> Path:
    """Write or verify the generated rule reference."""
    destination = path or project_root() / "docs" / "rules.md"
    expected = render_rule_reference()
    if check:
        if (
            not destination.is_file()
            or destination.read_text(encoding="utf-8") != expected
        ):
            raise RuntimeError(
                f"{destination} is stale; run `uv run lup-devtools dev rules`"
            )
        return destination
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8", newline="\n")
    return destination
