# lup: ignore[native-spelling]
# The rule-reference generator necessarily documents the spellings it audits.
"""Generate the checked-in Lup rule reference from canonical rule objects."""

import html
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from lup.codescan.antipatterns import PYTHON_ANTI_PATTERNS, TS_ANTI_PATTERNS
from lup.codescan.boundaries import (
    KERNEL_IMPORT_RULE_ID,
    NATIVE_SPELLING_RULE_ID,
    RULE_ID as SEAM_BOUNDARY_RULE_ID,
)
from lup.codescan.capabilities import RULE_ID as ABC_CAPABILITY_RULE_ID
from lup.workspace.paths import project_root


class RuleReference(BaseModel):
    """One documentation row projected from an executable rule."""

    model_config = ConfigDict(frozen=True)

    id: str
    scope: str
    example: str
    message: str


STRUCTURAL_RULES = [
    RuleReference(
        id=ABC_CAPABILITY_RULE_ID,
        scope="Python architecture",
        example="class Combined(Reader, Writer): ...",
        message=(
            "Capability ABCs stay independently constructible and cohesive; "
            "implementations do not inherit multiple capabilities or reusable behavior."
        ),
    ),
    RuleReference(
        id=SEAM_BOUNDARY_RULE_ID,
        scope="Neutral Python modules",
        example="from lup.adapters.codex.runtime import CodexSessionConfig",
        message=(
            "Concrete adapter imports belong only in adapters, tests, examples, and "
            "named application composition roots."
        ),
    ),
    RuleReference(
        id=NATIVE_SPELLING_RULE_ID,
        scope="Neutral Python modules",
        example='instruction = "$lup:commit"',
        message=(
            "Provider command, event, environment, and manifest spellings stay at "
            "the native adapter boundary."
        ),
    ),
    RuleReference(
        id=KERNEL_IMPORT_RULE_ID,
        scope="Policy kernel",
        example="from pydantic import BaseModel",
        message=(
            "The copied hook kernel imports only its pinned standard-library allowlist."
        ),
    ),
]


def anti_pattern_rows() -> list[RuleReference]:
    """Project canonical anti-pattern objects into documentation rows."""
    return [
        RuleReference(
            id=rule.id,
            scope=scope,
            example=rule.pattern.pattern,
            message=rule.message,
        )
        for scope, rules in (
            ("Python", PYTHON_ANTI_PATTERNS),
            ("TypeScript", TS_ANTI_PATTERNS),
        )
        for rule in rules
    ]


def markdown_cell(value: str) -> str:
    """Escape generated text for one Markdown table cell."""
    return html.escape(value).translate(str.maketrans({"|": "&#124;", "\n": " "}))


def render_rule_reference() -> str:
    """Render every executable Lup rule and typed-suppression convention."""
    structural = sorted(STRUCTURAL_RULES, key=lambda item: item.id)
    anti_patterns = sorted(anti_pattern_rows(), key=lambda item: (item.scope, item.id))

    def table(rows: list[RuleReference]) -> str:
        lines = [
            "| Rule id | Scope | Matching example | Diagnostic |",
            "|---|---|---|---|",
            *[
                "| "
                f"`{row.id}` | {markdown_cell(row.scope)} | "
                f"<code>{markdown_cell(row.example)}</code> | "
                f"{markdown_cell(row.message)} |"
                for row in rows
            ],
        ]
        return "\n".join(lines)

    return (
        "# Lup rule reference\n\n"
        "<!-- Generated by `uv run lup-devtools dev rules`; do not edit by hand. -->\n\n"
        "Lup rules enforce repository-specific architecture and editing conventions. "
        "Ruff remains the source of standard Python diagnostics. The matching examples "
        "for anti-patterns are their canonical regular-expression shapes, so this "
        "reference cannot drift from the edit hook or repository auditor.\n\n"
        "## Typed suppressions\n\n"
        "Suppress one deliberate site with `# lup: ignore[rule-id]` and a reason. "
        "Comma-separated ids cover a line that intentionally matches several rules. "
        "A typed directive in the first ten lines applies file-wide. Bare "
        "`# lup: ignore` remains parseable but is reported as untyped; a stale typed "
        "directive is blocking. `# noqa`, `# type: ignore`, and `# pyright: ignore` "
        "are separate forbidden shapes.\n\n"
        "```python\n"
        "cache: dict[str, int] = {}  # lup: ignore[empty-collection] — mutable fold\n"
        "```\n\n"
        "## Structural rules\n\n"
        f"{table(structural)}\n\n"
        "## Edit anti-patterns\n\n"
        f"{table(anti_patterns)}\n"
    )


def write_rule_reference(path: Path | None = None, *, check: bool = False) -> Path:
    """Write or verify the generated rule reference."""
    destination = path or project_root() / "docs" / "rules.md"
    expected = render_rule_reference()
    if check:
        if (
            not destination.is_file()
            or destination.read_text(encoding="utf-8") != expected
        ):
            raise RuntimeError(
                f"{destination} is stale; run `uv run lup-devtools dev rules`"
            )
        return destination
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8", newline="\n")
    return destination
