"""Canonical declaration for the report skill.

The topic roster and the scratch directory are read from the report surface's
own declaration rather than restated here, so the skill cannot come to describe
a report the command does not produce. Only the models are imported — nothing
that wires a CLI — because this prose is generated by that CLI.

The prose is laid out for what it renders to rather than for how it reads
here: a line wraps where the substituted directory leaves it, so a paragraph
built around the longer spelling comes out ragged in the file an agent reads.
"""

import lup.harness.models as models
from lup.formats.markdown import ProseStrong
from lup.devtools.report.models import DEFAULT_SCRATCH_ROOT, REPORT_TOPICS

SKILL = models.Skill(
    id="skill.report",
    name="report",
    description=(
        "Write the report of everything left to implement, rewritten whole"
        " under tmp/, after a long session or after implementing a plan"
    ),
    tools=["Bash(uv run lup-devtools:*)", "Read", "Write"],
    prompt=models.PromptDocument(
        source=__name__,
        parts=[
            models.Passage(
                module=__name__,
                values={
                    "default_scratch_root": models.plain(DEFAULT_SCRATCH_ROOT),
                    "topic_bullets": models.BulletList(
                        items=[
                            models.BulletItem(
                                lead=ProseStrong(text=topic.title), text=topic.guidance
                            )
                            for topic in REPORT_TOPICS
                        ]
                    ),
                },
            ),
        ],
    ),
)
