"""Generated application-owned policy data.

Rendered from lup.policy.bundle by
`uv run lup-devtools harness generate all` — do not edit directly.
"""

ALLOWED_FETCH_SCOPES = [
    (
        "https",
        "docs.claude.com",
        None,
        "/",
        "",
    ),
    (
        "http",
        "docs.claude.com",
        None,
        "/",
        "",
    ),
    (
        "https",
        "ai.pydantic.dev",
        None,
        "/",
        "",
    ),
    (
        "http",
        "ai.pydantic.dev",
        None,
        "/",
        "",
    ),
]

DENIED_FETCH_SCOPES = ()

PATH_RULES = [
    (
        "subtree",
        ".claude",
        "protected path requires approval",
        True,
    ),
    (
        "contains_part",
        "tmp",
        "scratch path requires approval",
        False,
    ),
    (
        "subtree",
        "pyproject.toml",
        "protected path requires approval",
        True,
    ),
    (
        "subtree",
        "sync.json",
        "protected path requires approval",
        True,
    ),
    (
        "subtree",
        "downstream.json",
        "protected path requires approval",
        True,
    ),
    (
        "exact",
        "README.md",
        "README.md is human-authored; propose changes via AskUserQuestion instead of editing",
        False,
    ),
    (
        "name_prefix",
        ".env",
        "protected path requires approval",
        True,
    ),
    (
        "new_devtools",
        "src",
        "new devtools module requires approval",
        False,
    ),
]

ANTI_PATTERN_ROWS = {
    ".js": [
        (
            "as-any",
            "\\bas\\s+any\\b",
            "Never use `as any` \u2014 use proper types or type guards",
            "code",
        ),
        (
            "as-unknown",
            "\\bas\\s+unknown\\b",
            "Never use `as unknown` \u2014 use type guards or proper types",
            "code",
        ),
        (
            "any-annotation",
            ":\\s*any\\b",
            "Never use `any` type annotation \u2014 use specific types, generics, or `unknown`",
            "code",
        ),
        (
            "any-assertion",
            "<any>",
            "Never use `<any>` type assertion \u2014 use proper types",
            "code",
        ),
        (
            "ts-ignore",
            "@ts-ignore",
            "Never use @ts-ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-expect-error",
            "@ts-expect-error",
            "Never use @ts-expect-error \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-nocheck",
            "@ts-nocheck",
            "Never use @ts-nocheck \u2014 fix the type errors in the file",
            "comment",
        ),
        (
            "eslint-disable",
            "//\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "eslint-disable-block",
            "/\\*\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "tslint-disable",
            "//\\s*tslint:disable",
            "Never use tslint:disable \u2014 migrate to eslint and fix the issue",
            "comment",
        ),
        (
            "non-null-assertion",
            "[\\w\\)\\]]!\\.",
            "Postfix `!.` non-null assertion hides a possible null/undefined \u2014 narrow the type or handle the missing case",
            "code",
        ),
        (
            "var-declaration",
            "\\bvar\\s+[A-Za-z_$]",
            "Use `const` or `let` instead of `var` \u2014 var is function-scoped and hoisted",
            "code",
        ),
        (
            "function-object-type",
            ":\\s*(?:Function|Object)\\b",
            "Never use `Function` or `Object` as a type \u2014 declare the call signature or the object shape",
            "code",
        ),
        (
            "console-log",
            "\\bconsole\\.log\\s*\\(",
            "console.log is a debug leftover \u2014 remove it or route through a logger",
            "code",
        ),
    ],
    ".jsx": [
        (
            "as-any",
            "\\bas\\s+any\\b",
            "Never use `as any` \u2014 use proper types or type guards",
            "code",
        ),
        (
            "as-unknown",
            "\\bas\\s+unknown\\b",
            "Never use `as unknown` \u2014 use type guards or proper types",
            "code",
        ),
        (
            "any-annotation",
            ":\\s*any\\b",
            "Never use `any` type annotation \u2014 use specific types, generics, or `unknown`",
            "code",
        ),
        (
            "any-assertion",
            "<any>",
            "Never use `<any>` type assertion \u2014 use proper types",
            "code",
        ),
        (
            "ts-ignore",
            "@ts-ignore",
            "Never use @ts-ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-expect-error",
            "@ts-expect-error",
            "Never use @ts-expect-error \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-nocheck",
            "@ts-nocheck",
            "Never use @ts-nocheck \u2014 fix the type errors in the file",
            "comment",
        ),
        (
            "eslint-disable",
            "//\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "eslint-disable-block",
            "/\\*\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "tslint-disable",
            "//\\s*tslint:disable",
            "Never use tslint:disable \u2014 migrate to eslint and fix the issue",
            "comment",
        ),
        (
            "non-null-assertion",
            "[\\w\\)\\]]!\\.",
            "Postfix `!.` non-null assertion hides a possible null/undefined \u2014 narrow the type or handle the missing case",
            "code",
        ),
        (
            "var-declaration",
            "\\bvar\\s+[A-Za-z_$]",
            "Use `const` or `let` instead of `var` \u2014 var is function-scoped and hoisted",
            "code",
        ),
        (
            "function-object-type",
            ":\\s*(?:Function|Object)\\b",
            "Never use `Function` or `Object` as a type \u2014 declare the call signature or the object shape",
            "code",
        ),
        (
            "console-log",
            "\\bconsole\\.log\\s*\\(",
            "console.log is a debug leftover \u2014 remove it or route through a logger",
            "code",
        ),
    ],
    ".py": [
        (
            "any-type",
            "\\bAny\\b",
            "Never use Any \u2014 use specific types, TypedDict, or BaseModel",
            "code",
        ),
        (
            "type-ignore",
            "#\\s*type:\\s*ignore",
            "Never use # type: ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "pyright-ignore",
            "#\\s*pyright:\\s*ignore",
            "Never use # pyright: ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "noqa",
            "#\\s*noqa\\b",
            "Never use # noqa \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "generic-base",
            "\\bGeneric\\[",
            "Use Python 3.12+ class[T] syntax instead of Generic[T]",
            "code",
        ),
        (
            "typing-union",
            "\\b(?:Optional|Union)\\[",
            "Use PEP 604 unions \u2014 X | None instead of Optional, X | Y instead of Union",
            "code",
        ),
        (
            "typing-generics",
            "\\b(?:List|Dict|Tuple|Set)\\[",
            "Use lowercase builtin generics \u2014 list, dict, tuple, set \u2014 instead of the capitalized typing aliases",
            "code",
        ),
        (
            "all-export",
            "__all__\\s*[=:]",
            "No __all__ \u2014 import directly from the defining module",
            "code",
        ),
        (
            "dict-str-object",
            "\\b(?:dict|Mapping)\\[\\s*str\\s*,\\s*object\\s*\\]",
            "Never use dict[str, object] or Mapping[str, object] \u2014 use TypedDict or BaseModel",
            "code",
        ),
        (
            "dict-str-payload",
            "\\b(?:dict|Mapping|MutableMapping)\\[\\s*str\\s*,\\s*(?:str|int|float|bool|bytes|complex)\\b",
            "String-keyed dict with a scalar value hides shape when the keys are a CLOSED, enumerable set \u2014 use a BaseModel or dict[Literal[...], V]. When the keys are open and data-driven (a registry/cache/counter keyed by external data) this is legitimate: add `# lup: ignore[dict-str-payload]`. Concrete class/callable value types (dict[str, SessionFactory]) are already accepted; JsonValue covers arbitrary JSON",
            "code",
        ),
        (
            "dict-get",
            "\\.get\\s*\\(",
            "`.get(` on payload/TypedDict-shaped data hides the schema \u2014 use typed attribute access (BaseModel/TypedDict). On a genuinely open dict (registry, cache) add `# lup: ignore[dict-get]`",
            "code",
        ),
        (
            "bare-object",
            "(?:(?<!\\w)(?!_)\\w+\\s*:|->)\\s*object\\b",
            "Bare `object` says nothing about the value \u2014 use a concrete type, TypedDict, or BaseModel, and narrow at untyped boundaries",
            "code",
        ),
        (
            "bare-basemodel",
            "(?:(?<!\\[)\\b\\w+\\s*:|->)\\s*BaseModel\\b(?!\\s*[\\]|])",
            "A parameter or return annotated exactly BaseModel accepts any model \u2014 name the concrete union of models or make the function generic",
            "code",
        ),
        (
            "tuple-shape",
            "\\btuple\\[",
            "A declared `tuple[...]` shape hides what each position means \u2014 name the fields with a TypedDict or BaseModel, a `type Alias = ...` for a reused shape, or `list` for a variable-length sequence",
            "code",
        ),
        (
            "frozenset-shape",
            "\\bfrozenset\\b",
            "A declared `frozenset[...]` shape or constant is usually overkill \u2014 use a dict or a purpose-built structure. For a genuinely immutable default argument add `# lup: ignore[frozenset-shape]`",
            "code",
        ),
        (
            "set-shape",
            "(?<!\\.)\\bset[\\[(]|(?::|->)\\s*set\\b",
            "A declared `set` is usually better as a dict (keyed lookup) or a purpose-built structure. For a genuinely set-shaped value add `# lup: ignore[set-shape]`",
            "code",
        ),
        (
            "empty-collection",
            "(?<![=!<>])=\\s*(?:\\{\\}|\\[\\]|set\\(\\))",
            "Empty-collection literals (`= {}`, `= []`, `= set()`) usually seed an append/mutate loop \u2014 build the collection with a comprehension instead, or add `# lup: ignore[empty-collection]` for a fold no comprehension can express",
            "code",
        ),
        (
            "cast",
            "\\bcast\\s*\\(",
            "`cast(...)` is a code smell \u2014 narrow with isinstance or a type guard, or fix the annotation so the cast is unnecessary",
            "code",
        ),
        (
            "import-re",
            "\\bimport\\s+re\\b|\\bfrom\\s+re\\s+import\\b",
            "`import re` / `from re import` is a code smell \u2014 parse structured data with its own API instead: JSON -> json.loads, paths -> pathlib.Path, URLs -> urllib.parse, XML/HTML -> xml.etree.ElementTree / lxml, dates -> datetime",
            "code",
        ),
        (
            "re-call",
            "\\bre\\.(compile|search|match|fullmatch|sub|findall|split)\\s*\\(",
            "Avoid regex for structured data \u2014 reach for its parser instead: JSON -> json.loads, paths -> pathlib.Path, URLs -> urllib.parse, XML/HTML -> xml.etree.ElementTree / lxml, dates -> datetime",
            "code",
        ),
        (
            "string-replace",
            "(?<!\\bos)(?<![Pp]ath)\\.replace\\s*\\(",
            "Avoid .replace() for structured data \u2014 edit it through its parser instead (pathlib.Path for paths, urllib.parse for URLs, json for JSON)",
            "code",
        ),
        (
            "string-split",
            "\\.r?split\\s*\\((?!\\s*\\))|\\.r?partition\\s*\\(",
            "Avoid .split(sep)/.rsplit/.partition for structured data \u2014 parse it instead (urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime for dates)",
            "code",
        ),
        (
            "string-strip",
            "\\.[lr]?strip\\s*\\((?!\\s*\\))",
            "Avoid .strip(chars)/.lstrip/.rstrip for structured data \u2014 parse it instead (urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime for dates)",
            "code",
        ),
        (
            "bare-except",
            "\\bexcept\\s*:",
            "Bare `except:` catches SystemExit/KeyboardInterrupt \u2014 name the exception",
            "code",
        ),
        (
            "except-baseexception",
            "\\bexcept\\s+BaseException\\b",
            "except BaseException catches KeyboardInterrupt \u2014 use Exception or narrower",
            "code",
        ),
        (
            "suppress",
            "\\bcontextlib\\.suppress\\b",
            "contextlib.suppress silently swallows exceptions \u2014 log, handle, or re-raise",
            "code",
        ),
        (
            "suppress-import",
            "\\bfrom\\s+contextlib\\s+import\\b.*\\bsuppress\\b",
            "contextlib.suppress silently swallows exceptions \u2014 log, handle, or re-raise",
            "code",
        ),
        (
            "dataclass",
            "@dataclass|\\bimport\\s+dataclasses\\b|\\bfrom\\s+dataclasses\\s+import\\b",
            "Use Pydantic BaseModel (or TypedDict) instead of dataclasses",
            "code",
        ),
        (
            "namedtuple",
            "\\bNamedTuple\\b|\\bnamedtuple\\b",
            "Use Pydantic BaseModel (or TypedDict) instead of NamedTuple/namedtuple",
            "code",
        ),
        (
            "subprocess",
            "\\bimport\\s+subprocess\\b|\\bfrom\\s+subprocess\\s+import\\b",
            "Use the `sh` library instead of subprocess",
            "code",
        ),
        (
            "os-shell",
            "\\bos\\.(?:system|popen|exec[lv]\\w*)\\s*\\(",
            "Use the `sh` library instead of os.system()/os.popen()/os.exec*()",
            "code",
        ),
        (
            "argparse",
            "\\bimport\\s+argparse\\b|\\bfrom\\s+argparse\\s+import\\b",
            "Use `typer` instead of argparse",
            "code",
        ),
        (
            "rich-progress",
            "\\brich\\.progress\\b|\\bfrom\\s+rich\\.progress\\s+import\\b",
            "Use `tqdm` instead of rich progress bars",
            "code",
        ),
        (
            "os-path",
            "\\bos\\.path\\b",
            "Use pathlib.Path instead of os.path",
            "code",
        ),
        (
            "os-file-ops",
            "\\bos\\.(?:getcwd|chdir|listdir|scandir|walk|mkdir|makedirs|rmdir|removedirs|remove|unlink|rename|renames|replace|link|symlink|readlink|stat|lstat|chmod|chown)\\s*\\(",
            "Use pathlib.Path for file/dir operations instead of os.* (Path.iterdir/mkdir/unlink/rename/replace/stat/...)",
            "code",
        ),
        (
            "os-environ",
            "\\bos\\.(?:environ|getenv)\\b",
            "Read configuration through pydantic-settings, not os.environ/os.getenv",
            "code",
        ),
        (
            "eval-exec",
            "(?<![.\\w])(?:eval|exec)\\s*\\(",
            "Never use eval()/exec() \u2014 parse the data (ast.literal_eval for literals) or dispatch explicitly",
            "code",
        ),
        (
            "utcnow",
            "\\butcnow\\s*\\(",
            "datetime.utcnow() is naive and deprecated \u2014 use datetime.now(timezone.utc)",
            "code",
        ),
        (
            "global-statement",
            "^global\\s+\\w",
            "No `global` statements \u2014 mutate a module-level holder object or pass state explicitly",
            "code",
        ),
        (
            "private-function",
            "\\bdef\\s+_[a-zA-Z]",
            "No `_` prefix on functions/methods \u2014 nothing is private (nest inside caller if needed)",
            "code",
        ),
        (
            "private-class",
            "\\bclass\\s+_[A-Z]",
            "No `_` prefix on classes \u2014 nothing is private",
            "code",
        ),
        (
            "private-variable",
            "^_[a-zA-Z]\\w*\\s*(?::[^=]*)?=(?!=)(?!.*,\\s*$)",
            "No `_` prefix on variables/constants \u2014 nothing is private (unused `_` function parameters are exempt)",
            "code",
        ),
    ],
    ".pyi": [
        (
            "any-type",
            "\\bAny\\b",
            "Never use Any \u2014 use specific types, TypedDict, or BaseModel",
            "code",
        ),
        (
            "type-ignore",
            "#\\s*type:\\s*ignore",
            "Never use # type: ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "pyright-ignore",
            "#\\s*pyright:\\s*ignore",
            "Never use # pyright: ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "noqa",
            "#\\s*noqa\\b",
            "Never use # noqa \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "generic-base",
            "\\bGeneric\\[",
            "Use Python 3.12+ class[T] syntax instead of Generic[T]",
            "code",
        ),
        (
            "typing-union",
            "\\b(?:Optional|Union)\\[",
            "Use PEP 604 unions \u2014 X | None instead of Optional, X | Y instead of Union",
            "code",
        ),
        (
            "typing-generics",
            "\\b(?:List|Dict|Tuple|Set)\\[",
            "Use lowercase builtin generics \u2014 list, dict, tuple, set \u2014 instead of the capitalized typing aliases",
            "code",
        ),
        (
            "all-export",
            "__all__\\s*[=:]",
            "No __all__ \u2014 import directly from the defining module",
            "code",
        ),
        (
            "dict-str-object",
            "\\b(?:dict|Mapping)\\[\\s*str\\s*,\\s*object\\s*\\]",
            "Never use dict[str, object] or Mapping[str, object] \u2014 use TypedDict or BaseModel",
            "code",
        ),
        (
            "dict-str-payload",
            "\\b(?:dict|Mapping|MutableMapping)\\[\\s*str\\s*,\\s*(?:str|int|float|bool|bytes|complex)\\b",
            "String-keyed dict with a scalar value hides shape when the keys are a CLOSED, enumerable set \u2014 use a BaseModel or dict[Literal[...], V]. When the keys are open and data-driven (a registry/cache/counter keyed by external data) this is legitimate: add `# lup: ignore[dict-str-payload]`. Concrete class/callable value types (dict[str, SessionFactory]) are already accepted; JsonValue covers arbitrary JSON",
            "code",
        ),
        (
            "dict-get",
            "\\.get\\s*\\(",
            "`.get(` on payload/TypedDict-shaped data hides the schema \u2014 use typed attribute access (BaseModel/TypedDict). On a genuinely open dict (registry, cache) add `# lup: ignore[dict-get]`",
            "code",
        ),
        (
            "bare-object",
            "(?:(?<!\\w)(?!_)\\w+\\s*:|->)\\s*object\\b",
            "Bare `object` says nothing about the value \u2014 use a concrete type, TypedDict, or BaseModel, and narrow at untyped boundaries",
            "code",
        ),
        (
            "bare-basemodel",
            "(?:(?<!\\[)\\b\\w+\\s*:|->)\\s*BaseModel\\b(?!\\s*[\\]|])",
            "A parameter or return annotated exactly BaseModel accepts any model \u2014 name the concrete union of models or make the function generic",
            "code",
        ),
        (
            "tuple-shape",
            "\\btuple\\[",
            "A declared `tuple[...]` shape hides what each position means \u2014 name the fields with a TypedDict or BaseModel, a `type Alias = ...` for a reused shape, or `list` for a variable-length sequence",
            "code",
        ),
        (
            "frozenset-shape",
            "\\bfrozenset\\b",
            "A declared `frozenset[...]` shape or constant is usually overkill \u2014 use a dict or a purpose-built structure. For a genuinely immutable default argument add `# lup: ignore[frozenset-shape]`",
            "code",
        ),
        (
            "set-shape",
            "(?<!\\.)\\bset[\\[(]|(?::|->)\\s*set\\b",
            "A declared `set` is usually better as a dict (keyed lookup) or a purpose-built structure. For a genuinely set-shaped value add `# lup: ignore[set-shape]`",
            "code",
        ),
        (
            "empty-collection",
            "(?<![=!<>])=\\s*(?:\\{\\}|\\[\\]|set\\(\\))",
            "Empty-collection literals (`= {}`, `= []`, `= set()`) usually seed an append/mutate loop \u2014 build the collection with a comprehension instead, or add `# lup: ignore[empty-collection]` for a fold no comprehension can express",
            "code",
        ),
        (
            "cast",
            "\\bcast\\s*\\(",
            "`cast(...)` is a code smell \u2014 narrow with isinstance or a type guard, or fix the annotation so the cast is unnecessary",
            "code",
        ),
        (
            "import-re",
            "\\bimport\\s+re\\b|\\bfrom\\s+re\\s+import\\b",
            "`import re` / `from re import` is a code smell \u2014 parse structured data with its own API instead: JSON -> json.loads, paths -> pathlib.Path, URLs -> urllib.parse, XML/HTML -> xml.etree.ElementTree / lxml, dates -> datetime",
            "code",
        ),
        (
            "re-call",
            "\\bre\\.(compile|search|match|fullmatch|sub|findall|split)\\s*\\(",
            "Avoid regex for structured data \u2014 reach for its parser instead: JSON -> json.loads, paths -> pathlib.Path, URLs -> urllib.parse, XML/HTML -> xml.etree.ElementTree / lxml, dates -> datetime",
            "code",
        ),
        (
            "string-replace",
            "(?<!\\bos)(?<![Pp]ath)\\.replace\\s*\\(",
            "Avoid .replace() for structured data \u2014 edit it through its parser instead (pathlib.Path for paths, urllib.parse for URLs, json for JSON)",
            "code",
        ),
        (
            "string-split",
            "\\.r?split\\s*\\((?!\\s*\\))|\\.r?partition\\s*\\(",
            "Avoid .split(sep)/.rsplit/.partition for structured data \u2014 parse it instead (urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime for dates)",
            "code",
        ),
        (
            "string-strip",
            "\\.[lr]?strip\\s*\\((?!\\s*\\))",
            "Avoid .strip(chars)/.lstrip/.rstrip for structured data \u2014 parse it instead (urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime for dates)",
            "code",
        ),
        (
            "bare-except",
            "\\bexcept\\s*:",
            "Bare `except:` catches SystemExit/KeyboardInterrupt \u2014 name the exception",
            "code",
        ),
        (
            "except-baseexception",
            "\\bexcept\\s+BaseException\\b",
            "except BaseException catches KeyboardInterrupt \u2014 use Exception or narrower",
            "code",
        ),
        (
            "suppress",
            "\\bcontextlib\\.suppress\\b",
            "contextlib.suppress silently swallows exceptions \u2014 log, handle, or re-raise",
            "code",
        ),
        (
            "suppress-import",
            "\\bfrom\\s+contextlib\\s+import\\b.*\\bsuppress\\b",
            "contextlib.suppress silently swallows exceptions \u2014 log, handle, or re-raise",
            "code",
        ),
        (
            "dataclass",
            "@dataclass|\\bimport\\s+dataclasses\\b|\\bfrom\\s+dataclasses\\s+import\\b",
            "Use Pydantic BaseModel (or TypedDict) instead of dataclasses",
            "code",
        ),
        (
            "namedtuple",
            "\\bNamedTuple\\b|\\bnamedtuple\\b",
            "Use Pydantic BaseModel (or TypedDict) instead of NamedTuple/namedtuple",
            "code",
        ),
        (
            "subprocess",
            "\\bimport\\s+subprocess\\b|\\bfrom\\s+subprocess\\s+import\\b",
            "Use the `sh` library instead of subprocess",
            "code",
        ),
        (
            "os-shell",
            "\\bos\\.(?:system|popen|exec[lv]\\w*)\\s*\\(",
            "Use the `sh` library instead of os.system()/os.popen()/os.exec*()",
            "code",
        ),
        (
            "argparse",
            "\\bimport\\s+argparse\\b|\\bfrom\\s+argparse\\s+import\\b",
            "Use `typer` instead of argparse",
            "code",
        ),
        (
            "rich-progress",
            "\\brich\\.progress\\b|\\bfrom\\s+rich\\.progress\\s+import\\b",
            "Use `tqdm` instead of rich progress bars",
            "code",
        ),
        (
            "os-path",
            "\\bos\\.path\\b",
            "Use pathlib.Path instead of os.path",
            "code",
        ),
        (
            "os-file-ops",
            "\\bos\\.(?:getcwd|chdir|listdir|scandir|walk|mkdir|makedirs|rmdir|removedirs|remove|unlink|rename|renames|replace|link|symlink|readlink|stat|lstat|chmod|chown)\\s*\\(",
            "Use pathlib.Path for file/dir operations instead of os.* (Path.iterdir/mkdir/unlink/rename/replace/stat/...)",
            "code",
        ),
        (
            "os-environ",
            "\\bos\\.(?:environ|getenv)\\b",
            "Read configuration through pydantic-settings, not os.environ/os.getenv",
            "code",
        ),
        (
            "eval-exec",
            "(?<![.\\w])(?:eval|exec)\\s*\\(",
            "Never use eval()/exec() \u2014 parse the data (ast.literal_eval for literals) or dispatch explicitly",
            "code",
        ),
        (
            "utcnow",
            "\\butcnow\\s*\\(",
            "datetime.utcnow() is naive and deprecated \u2014 use datetime.now(timezone.utc)",
            "code",
        ),
        (
            "global-statement",
            "^global\\s+\\w",
            "No `global` statements \u2014 mutate a module-level holder object or pass state explicitly",
            "code",
        ),
        (
            "private-function",
            "\\bdef\\s+_[a-zA-Z]",
            "No `_` prefix on functions/methods \u2014 nothing is private (nest inside caller if needed)",
            "code",
        ),
        (
            "private-class",
            "\\bclass\\s+_[A-Z]",
            "No `_` prefix on classes \u2014 nothing is private",
            "code",
        ),
        (
            "private-variable",
            "^_[a-zA-Z]\\w*\\s*(?::[^=]*)?=(?!=)(?!.*,\\s*$)",
            "No `_` prefix on variables/constants \u2014 nothing is private (unused `_` function parameters are exempt)",
            "code",
        ),
    ],
    ".svelte": [
        (
            "as-any",
            "\\bas\\s+any\\b",
            "Never use `as any` \u2014 use proper types or type guards",
            "code",
        ),
        (
            "as-unknown",
            "\\bas\\s+unknown\\b",
            "Never use `as unknown` \u2014 use type guards or proper types",
            "code",
        ),
        (
            "any-annotation",
            ":\\s*any\\b",
            "Never use `any` type annotation \u2014 use specific types, generics, or `unknown`",
            "code",
        ),
        (
            "any-assertion",
            "<any>",
            "Never use `<any>` type assertion \u2014 use proper types",
            "code",
        ),
        (
            "ts-ignore",
            "@ts-ignore",
            "Never use @ts-ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-expect-error",
            "@ts-expect-error",
            "Never use @ts-expect-error \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-nocheck",
            "@ts-nocheck",
            "Never use @ts-nocheck \u2014 fix the type errors in the file",
            "comment",
        ),
        (
            "eslint-disable",
            "//\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "eslint-disable-block",
            "/\\*\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "tslint-disable",
            "//\\s*tslint:disable",
            "Never use tslint:disable \u2014 migrate to eslint and fix the issue",
            "comment",
        ),
        (
            "non-null-assertion",
            "[\\w\\)\\]]!\\.",
            "Postfix `!.` non-null assertion hides a possible null/undefined \u2014 narrow the type or handle the missing case",
            "code",
        ),
        (
            "var-declaration",
            "\\bvar\\s+[A-Za-z_$]",
            "Use `const` or `let` instead of `var` \u2014 var is function-scoped and hoisted",
            "code",
        ),
        (
            "function-object-type",
            ":\\s*(?:Function|Object)\\b",
            "Never use `Function` or `Object` as a type \u2014 declare the call signature or the object shape",
            "code",
        ),
        (
            "console-log",
            "\\bconsole\\.log\\s*\\(",
            "console.log is a debug leftover \u2014 remove it or route through a logger",
            "code",
        ),
    ],
    ".ts": [
        (
            "as-any",
            "\\bas\\s+any\\b",
            "Never use `as any` \u2014 use proper types or type guards",
            "code",
        ),
        (
            "as-unknown",
            "\\bas\\s+unknown\\b",
            "Never use `as unknown` \u2014 use type guards or proper types",
            "code",
        ),
        (
            "any-annotation",
            ":\\s*any\\b",
            "Never use `any` type annotation \u2014 use specific types, generics, or `unknown`",
            "code",
        ),
        (
            "any-assertion",
            "<any>",
            "Never use `<any>` type assertion \u2014 use proper types",
            "code",
        ),
        (
            "ts-ignore",
            "@ts-ignore",
            "Never use @ts-ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-expect-error",
            "@ts-expect-error",
            "Never use @ts-expect-error \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-nocheck",
            "@ts-nocheck",
            "Never use @ts-nocheck \u2014 fix the type errors in the file",
            "comment",
        ),
        (
            "eslint-disable",
            "//\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "eslint-disable-block",
            "/\\*\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "tslint-disable",
            "//\\s*tslint:disable",
            "Never use tslint:disable \u2014 migrate to eslint and fix the issue",
            "comment",
        ),
        (
            "non-null-assertion",
            "[\\w\\)\\]]!\\.",
            "Postfix `!.` non-null assertion hides a possible null/undefined \u2014 narrow the type or handle the missing case",
            "code",
        ),
        (
            "var-declaration",
            "\\bvar\\s+[A-Za-z_$]",
            "Use `const` or `let` instead of `var` \u2014 var is function-scoped and hoisted",
            "code",
        ),
        (
            "function-object-type",
            ":\\s*(?:Function|Object)\\b",
            "Never use `Function` or `Object` as a type \u2014 declare the call signature or the object shape",
            "code",
        ),
        (
            "console-log",
            "\\bconsole\\.log\\s*\\(",
            "console.log is a debug leftover \u2014 remove it or route through a logger",
            "code",
        ),
    ],
    ".tsx": [
        (
            "as-any",
            "\\bas\\s+any\\b",
            "Never use `as any` \u2014 use proper types or type guards",
            "code",
        ),
        (
            "as-unknown",
            "\\bas\\s+unknown\\b",
            "Never use `as unknown` \u2014 use type guards or proper types",
            "code",
        ),
        (
            "any-annotation",
            ":\\s*any\\b",
            "Never use `any` type annotation \u2014 use specific types, generics, or `unknown`",
            "code",
        ),
        (
            "any-assertion",
            "<any>",
            "Never use `<any>` type assertion \u2014 use proper types",
            "code",
        ),
        (
            "ts-ignore",
            "@ts-ignore",
            "Never use @ts-ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-expect-error",
            "@ts-expect-error",
            "Never use @ts-expect-error \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-nocheck",
            "@ts-nocheck",
            "Never use @ts-nocheck \u2014 fix the type errors in the file",
            "comment",
        ),
        (
            "eslint-disable",
            "//\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "eslint-disable-block",
            "/\\*\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "tslint-disable",
            "//\\s*tslint:disable",
            "Never use tslint:disable \u2014 migrate to eslint and fix the issue",
            "comment",
        ),
        (
            "non-null-assertion",
            "[\\w\\)\\]]!\\.",
            "Postfix `!.` non-null assertion hides a possible null/undefined \u2014 narrow the type or handle the missing case",
            "code",
        ),
        (
            "var-declaration",
            "\\bvar\\s+[A-Za-z_$]",
            "Use `const` or `let` instead of `var` \u2014 var is function-scoped and hoisted",
            "code",
        ),
        (
            "function-object-type",
            ":\\s*(?:Function|Object)\\b",
            "Never use `Function` or `Object` as a type \u2014 declare the call signature or the object shape",
            "code",
        ),
        (
            "console-log",
            "\\bconsole\\.log\\s*\\(",
            "console.log is a debug leftover \u2014 remove it or route through a logger",
            "code",
        ),
    ],
    ".vue": [
        (
            "as-any",
            "\\bas\\s+any\\b",
            "Never use `as any` \u2014 use proper types or type guards",
            "code",
        ),
        (
            "as-unknown",
            "\\bas\\s+unknown\\b",
            "Never use `as unknown` \u2014 use type guards or proper types",
            "code",
        ),
        (
            "any-annotation",
            ":\\s*any\\b",
            "Never use `any` type annotation \u2014 use specific types, generics, or `unknown`",
            "code",
        ),
        (
            "any-assertion",
            "<any>",
            "Never use `<any>` type assertion \u2014 use proper types",
            "code",
        ),
        (
            "ts-ignore",
            "@ts-ignore",
            "Never use @ts-ignore \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-expect-error",
            "@ts-expect-error",
            "Never use @ts-expect-error \u2014 fix the type error properly",
            "comment",
        ),
        (
            "ts-nocheck",
            "@ts-nocheck",
            "Never use @ts-nocheck \u2014 fix the type errors in the file",
            "comment",
        ),
        (
            "eslint-disable",
            "//\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "eslint-disable-block",
            "/\\*\\s*eslint-disable",
            "Never use eslint-disable \u2014 fix the lint issue properly",
            "comment",
        ),
        (
            "tslint-disable",
            "//\\s*tslint:disable",
            "Never use tslint:disable \u2014 migrate to eslint and fix the issue",
            "comment",
        ),
        (
            "non-null-assertion",
            "[\\w\\)\\]]!\\.",
            "Postfix `!.` non-null assertion hides a possible null/undefined \u2014 narrow the type or handle the missing case",
            "code",
        ),
        (
            "var-declaration",
            "\\bvar\\s+[A-Za-z_$]",
            "Use `const` or `let` instead of `var` \u2014 var is function-scoped and hoisted",
            "code",
        ),
        (
            "function-object-type",
            ":\\s*(?:Function|Object)\\b",
            "Never use `Function` or `Object` as a type \u2014 declare the call signature or the object shape",
            "code",
        ),
        (
            "console-log",
            "\\bconsole\\.log\\s*\\(",
            "console.log is a debug leftover \u2014 remove it or route through a logger",
            "code",
        ),
    ],
}

AUTONOMOUS_AGENT_IDENTITIES = [
    "resolve-editor",
    "lup:resolve-editor",
]

MAXIMUM_ADDED_LINES = 3
