"""Generated application-owned policy data."""

ALLOWED_FETCH_SCOPES = [('https', 'docs.claude.com', None, '/', ''),
 ('http', 'docs.claude.com', None, '/', ''),
 ('https', 'ai.pydantic.dev', None, '/', ''),
 ('http', 'ai.pydantic.dev', None, '/', '')]

DENIED_FETCH_SCOPES = ()

PATH_RULES = [('subtree', '.claude', 'protected path requires approval', True),
 ('contains_part', 'tmp', 'scratch path requires approval', False),
 ('subtree', 'pyproject.toml', 'protected path requires approval', True),
 ('name_prefix', '.env', 'protected path requires approval', True),
 ('new_devtools', 'src', 'new devtools module requires approval', False)]

ANTI_PATTERN_ROWS = {'.js': [('as-any',
          '\\bas\\s+any\\b',
          'Never use `as any` — use proper types or type guards'),
         ('as-unknown',
          '\\bas\\s+unknown\\b',
          'Never use `as unknown` — use type guards or proper types'),
         ('any-annotation',
          ':\\s*any\\b',
          'Never use `any` type annotation — use specific types, generics, or '
          '`unknown`'),
         ('any-assertion',
          '<any>',
          'Never use `<any>` type assertion — use proper types'),
         ('ts-ignore',
          '@ts-ignore',
          'Never use @ts-ignore — fix the type error properly'),
         ('ts-expect-error',
          '@ts-expect-error',
          'Never use @ts-expect-error — fix the type error properly'),
         ('ts-nocheck',
          '@ts-nocheck',
          'Never use @ts-nocheck — fix the type errors in the file'),
         ('eslint-disable',
          '//\\s*eslint-disable',
          'Never use eslint-disable — fix the lint issue properly'),
         ('eslint-disable-block',
          '/\\*\\s*eslint-disable',
          'Never use eslint-disable — fix the lint issue properly'),
         ('tslint-disable',
          '//\\s*tslint:disable',
          'Never use tslint:disable — migrate to eslint and fix the issue'),
         ('non-null-assertion',
          '[\\w\\)\\]]!\\.',
          'Postfix `!.` non-null assertion hides a possible null/undefined — narrow '
          'the type or handle the missing case'),
         ('var-declaration',
          '\\bvar\\s+[A-Za-z_$]',
          'Use `const` or `let` instead of `var` — var is function-scoped and hoisted'),
         ('function-object-type',
          ':\\s*(?:Function|Object)\\b',
          'Never use `Function` or `Object` as a type — declare the call signature or '
          'the object shape'),
         ('console-log',
          '\\bconsole\\.log\\s*\\(',
          'console.log is a debug leftover — remove it or route through a logger')],
 '.jsx': [('as-any',
           '\\bas\\s+any\\b',
           'Never use `as any` — use proper types or type guards'),
          ('as-unknown',
           '\\bas\\s+unknown\\b',
           'Never use `as unknown` — use type guards or proper types'),
          ('any-annotation',
           ':\\s*any\\b',
           'Never use `any` type annotation — use specific types, generics, or '
           '`unknown`'),
          ('any-assertion',
           '<any>',
           'Never use `<any>` type assertion — use proper types'),
          ('ts-ignore',
           '@ts-ignore',
           'Never use @ts-ignore — fix the type error properly'),
          ('ts-expect-error',
           '@ts-expect-error',
           'Never use @ts-expect-error — fix the type error properly'),
          ('ts-nocheck',
           '@ts-nocheck',
           'Never use @ts-nocheck — fix the type errors in the file'),
          ('eslint-disable',
           '//\\s*eslint-disable',
           'Never use eslint-disable — fix the lint issue properly'),
          ('eslint-disable-block',
           '/\\*\\s*eslint-disable',
           'Never use eslint-disable — fix the lint issue properly'),
          ('tslint-disable',
           '//\\s*tslint:disable',
           'Never use tslint:disable — migrate to eslint and fix the issue'),
          ('non-null-assertion',
           '[\\w\\)\\]]!\\.',
           'Postfix `!.` non-null assertion hides a possible null/undefined — narrow '
           'the type or handle the missing case'),
          ('var-declaration',
           '\\bvar\\s+[A-Za-z_$]',
           'Use `const` or `let` instead of `var` — var is function-scoped and '
           'hoisted'),
          ('function-object-type',
           ':\\s*(?:Function|Object)\\b',
           'Never use `Function` or `Object` as a type — declare the call signature or '
           'the object shape'),
          ('console-log',
           '\\bconsole\\.log\\s*\\(',
           'console.log is a debug leftover — remove it or route through a logger')],
 '.py': [('any-type',
          '\\bAny\\b',
          'Never use Any — use specific types, TypedDict, or BaseModel'),
         ('type-ignore',
          '#\\s*type:\\s*ignore',
          'Never use # type: ignore — fix the type error properly'),
         ('pyright-ignore',
          '#\\s*pyright:\\s*ignore',
          'Never use # pyright: ignore — fix the type error properly'),
         ('noqa', '#\\s*noqa\\b', 'Never use # noqa — fix the lint issue properly'),
         ('generic-base',
          '\\bGeneric\\[',
          'Use Python 3.12+ class[T] syntax instead of Generic[T]'),
         ('typing-union',
          '\\b(?:Optional|Union)\\[',
          'Use PEP 604 unions — X | None instead of Optional, X | Y instead of Union'),
         ('typing-generics',
          '\\b(?:List|Dict|Tuple|Set)\\[',
          'Use lowercase builtin generics — list, dict, tuple, set — instead of the '
          'capitalized typing aliases'),
         ('all-export',
          '__all__\\s*[=:]',
          'No __all__ — import directly from the defining module'),
         ('dict-str-object',
          '\\b(?:dict|Mapping)\\[\\s*str\\s*,\\s*object\\s*\\]',
          'Never use dict[str, object] or Mapping[str, object] — use TypedDict or '
          'BaseModel'),
         ('dict-str-payload',
          '\\b(?:dict|Mapping|MutableMapping)\\[\\s*str\\s*,\\s*(?:str|int|float|bool|bytes|complex)\\b',
          'String-keyed dict with a scalar value hides shape when the keys are a '
          'CLOSED, enumerable set — use a BaseModel or dict[Literal[...], V]. When the '
          'keys are open and data-driven (a registry/cache/counter keyed by external '
          'data) this is legitimate: add `# lup: ignore[dict-str-payload]`. Concrete '
          'class/callable value types (dict[str, SessionFactory]) are already '
          'accepted; JsonValue covers arbitrary JSON'),
         ('dict-get',
          '\\.get\\s*\\(',
          '`.get(` on payload/TypedDict-shaped data hides the schema — use typed '
          'attribute access (BaseModel/TypedDict). On a genuinely open dict (registry, '
          'cache) add `# lup: ignore[dict-get]`'),
         ('bare-object',
          '(?:(?<!\\w)(?!_)\\w+\\s*:|->)\\s*object\\b',
          'Bare `object` says nothing about the value — use a concrete type, '
          'TypedDict, or BaseModel, and narrow at untyped boundaries'),
         ('bare-basemodel',
          '(?:(?<!\\[)\\b\\w+\\s*:|->)\\s*BaseModel\\b(?!\\s*[\\]|])',
          'A parameter or return annotated exactly BaseModel accepts any model — name '
          'the concrete union of models or make the function generic'),
         ('tuple-shape',
          '\\btuple\\[',
          'A declared `tuple[...]` shape hides what each position means — name the '
          'fields with a TypedDict or BaseModel, a `type Alias = ...` for a reused '
          'shape, or `list` for a variable-length sequence'),
         ('frozenset-shape',
          '\\bfrozenset\\b',
          'A declared `frozenset[...]` shape or constant is usually overkill — use a '
          'dict or a purpose-built structure. For a genuinely immutable default '
          'argument add `# lup: ignore[frozenset-shape]`'),
         ('set-shape',
          '(?<!\\.)\\bset[\\[(]|(?::|->)\\s*set\\b',
          'A declared `set` is usually better as a dict (keyed lookup) or a '
          'purpose-built structure. For a genuinely set-shaped value add `# lup: '
          'ignore[set-shape]`'),
         ('empty-collection',
          '(?<![=!<>])=\\s*(?:\\{\\}|\\[\\]|set\\(\\))',
          'Empty-collection literals (`= {}`, `= []`, `= set()`) usually seed an '
          'append/mutate loop — build the collection with a comprehension instead, or '
          'add `# lup: ignore[empty-collection]` for a fold no comprehension can '
          'express'),
         ('cast',
          '\\bcast\\s*\\(',
          '`cast(...)` is a code smell — narrow with isinstance or a type guard, or '
          'fix the annotation so the cast is unnecessary'),
         ('import-re',
          '\\bimport\\s+re\\b|\\bfrom\\s+re\\s+import\\b',
          '`import re` / `from re import` is a code smell — parse structured data with '
          'its own API instead: JSON -> json.loads, paths -> pathlib.Path, URLs -> '
          'urllib.parse, XML/HTML -> xml.etree.ElementTree / lxml, dates -> datetime'),
         ('re-call',
          '\\bre\\.(compile|search|match|fullmatch|sub|findall|split)\\s*\\(',
          'Avoid regex for structured data — reach for its parser instead: JSON -> '
          'json.loads, paths -> pathlib.Path, URLs -> urllib.parse, XML/HTML -> '
          'xml.etree.ElementTree / lxml, dates -> datetime'),
         ('string-replace',
          '(?<!\\bos)(?<![Pp]ath)\\.replace\\s*\\(',
          'Avoid .replace() for structured data — edit it through its parser instead '
          '(pathlib.Path for paths, urllib.parse for URLs, json for JSON)'),
         ('string-split',
          '\\.r?split\\s*\\((?!\\s*\\))|\\.r?partition\\s*\\(',
          'Avoid .split(sep)/.rsplit/.partition for structured data — parse it instead '
          '(urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime for '
          'dates)'),
         ('string-strip',
          '\\.[lr]?strip\\s*\\((?!\\s*\\))',
          'Avoid .strip(chars)/.lstrip/.rstrip for structured data — parse it instead '
          '(urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime for '
          'dates)'),
         ('bare-except',
          '\\bexcept\\s*:',
          'Bare `except:` catches SystemExit/KeyboardInterrupt — name the exception'),
         ('except-baseexception',
          '\\bexcept\\s+BaseException\\b',
          'except BaseException catches KeyboardInterrupt — use Exception or narrower'),
         ('suppress',
          '\\bcontextlib\\.suppress\\b',
          'contextlib.suppress silently swallows exceptions — log, handle, or '
          're-raise'),
         ('suppress-import',
          '\\bfrom\\s+contextlib\\s+import\\b.*\\bsuppress\\b',
          'contextlib.suppress silently swallows exceptions — log, handle, or '
          're-raise'),
         ('dataclass',
          '@dataclass|\\bimport\\s+dataclasses\\b|\\bfrom\\s+dataclasses\\s+import\\b',
          'Use Pydantic BaseModel (or TypedDict) instead of dataclasses'),
         ('namedtuple',
          '\\bNamedTuple\\b|\\bnamedtuple\\b',
          'Use Pydantic BaseModel (or TypedDict) instead of NamedTuple/namedtuple'),
         ('subprocess',
          '\\bimport\\s+subprocess\\b|\\bfrom\\s+subprocess\\s+import\\b',
          'Use the `sh` library instead of subprocess'),
         ('os-shell',
          '\\bos\\.(?:system|popen|exec[lv]\\w*)\\s*\\(',
          'Use the `sh` library instead of os.system()/os.popen()/os.exec*()'),
         ('argparse',
          '\\bimport\\s+argparse\\b|\\bfrom\\s+argparse\\s+import\\b',
          'Use `typer` instead of argparse'),
         ('rich-progress',
          '\\brich\\.progress\\b|\\bfrom\\s+rich\\.progress\\s+import\\b',
          'Use `tqdm` instead of rich progress bars'),
         ('os-path', '\\bos\\.path\\b', 'Use pathlib.Path instead of os.path'),
         ('os-file-ops',
          '\\bos\\.(?:getcwd|chdir|listdir|scandir|walk|mkdir|makedirs|rmdir|removedirs|remove|unlink|rename|renames|replace|link|symlink|readlink|stat|lstat|chmod|chown)\\s*\\(',
          'Use pathlib.Path for file/dir operations instead of os.* '
          '(Path.iterdir/mkdir/unlink/rename/replace/stat/...)'),
         ('os-environ',
          '\\bos\\.(?:environ|getenv)\\b',
          'Read configuration through pydantic-settings, not os.environ/os.getenv'),
         ('eval-exec',
          '(?<![.\\w])(?:eval|exec)\\s*\\(',
          'Never use eval()/exec() — parse the data (ast.literal_eval for literals) or '
          'dispatch explicitly'),
         ('utcnow',
          '\\butcnow\\s*\\(',
          'datetime.utcnow() is naive and deprecated — use datetime.now(timezone.utc)'),
         ('global-statement',
          '^global\\s+\\w',
          'No `global` statements — mutate a module-level holder object or pass state '
          'explicitly'),
         ('private-function',
          '\\bdef\\s+_[a-zA-Z]',
          'No `_` prefix on functions/methods — nothing is private (nest inside caller '
          'if needed)'),
         ('private-class',
          '\\bclass\\s+_[A-Z]',
          'No `_` prefix on classes — nothing is private'),
         ('private-variable',
          '^_[a-zA-Z]\\w*\\s*(?::[^=]*)?=(?!=)(?!.*,\\s*$)',
          'No `_` prefix on variables/constants — nothing is private (unused `_` '
          'function parameters are exempt)')],
 '.pyi': [('any-type',
           '\\bAny\\b',
           'Never use Any — use specific types, TypedDict, or BaseModel'),
          ('type-ignore',
           '#\\s*type:\\s*ignore',
           'Never use # type: ignore — fix the type error properly'),
          ('pyright-ignore',
           '#\\s*pyright:\\s*ignore',
           'Never use # pyright: ignore — fix the type error properly'),
          ('noqa', '#\\s*noqa\\b', 'Never use # noqa — fix the lint issue properly'),
          ('generic-base',
           '\\bGeneric\\[',
           'Use Python 3.12+ class[T] syntax instead of Generic[T]'),
          ('typing-union',
           '\\b(?:Optional|Union)\\[',
           'Use PEP 604 unions — X | None instead of Optional, X | Y instead of Union'),
          ('typing-generics',
           '\\b(?:List|Dict|Tuple|Set)\\[',
           'Use lowercase builtin generics — list, dict, tuple, set — instead of the '
           'capitalized typing aliases'),
          ('all-export',
           '__all__\\s*[=:]',
           'No __all__ — import directly from the defining module'),
          ('dict-str-object',
           '\\b(?:dict|Mapping)\\[\\s*str\\s*,\\s*object\\s*\\]',
           'Never use dict[str, object] or Mapping[str, object] — use TypedDict or '
           'BaseModel'),
          ('dict-str-payload',
           '\\b(?:dict|Mapping|MutableMapping)\\[\\s*str\\s*,\\s*(?:str|int|float|bool|bytes|complex)\\b',
           'String-keyed dict with a scalar value hides shape when the keys are a '
           'CLOSED, enumerable set — use a BaseModel or dict[Literal[...], V]. When '
           'the keys are open and data-driven (a registry/cache/counter keyed by '
           'external data) this is legitimate: add `# lup: ignore[dict-str-payload]`. '
           'Concrete class/callable value types (dict[str, SessionFactory]) are '
           'already accepted; JsonValue covers arbitrary JSON'),
          ('dict-get',
           '\\.get\\s*\\(',
           '`.get(` on payload/TypedDict-shaped data hides the schema — use typed '
           'attribute access (BaseModel/TypedDict). On a genuinely open dict '
           '(registry, cache) add `# lup: ignore[dict-get]`'),
          ('bare-object',
           '(?:(?<!\\w)(?!_)\\w+\\s*:|->)\\s*object\\b',
           'Bare `object` says nothing about the value — use a concrete type, '
           'TypedDict, or BaseModel, and narrow at untyped boundaries'),
          ('bare-basemodel',
           '(?:(?<!\\[)\\b\\w+\\s*:|->)\\s*BaseModel\\b(?!\\s*[\\]|])',
           'A parameter or return annotated exactly BaseModel accepts any model — name '
           'the concrete union of models or make the function generic'),
          ('tuple-shape',
           '\\btuple\\[',
           'A declared `tuple[...]` shape hides what each position means — name the '
           'fields with a TypedDict or BaseModel, a `type Alias = ...` for a reused '
           'shape, or `list` for a variable-length sequence'),
          ('frozenset-shape',
           '\\bfrozenset\\b',
           'A declared `frozenset[...]` shape or constant is usually overkill — use a '
           'dict or a purpose-built structure. For a genuinely immutable default '
           'argument add `# lup: ignore[frozenset-shape]`'),
          ('set-shape',
           '(?<!\\.)\\bset[\\[(]|(?::|->)\\s*set\\b',
           'A declared `set` is usually better as a dict (keyed lookup) or a '
           'purpose-built structure. For a genuinely set-shaped value add `# lup: '
           'ignore[set-shape]`'),
          ('empty-collection',
           '(?<![=!<>])=\\s*(?:\\{\\}|\\[\\]|set\\(\\))',
           'Empty-collection literals (`= {}`, `= []`, `= set()`) usually seed an '
           'append/mutate loop — build the collection with a comprehension instead, or '
           'add `# lup: ignore[empty-collection]` for a fold no comprehension can '
           'express'),
          ('cast',
           '\\bcast\\s*\\(',
           '`cast(...)` is a code smell — narrow with isinstance or a type guard, or '
           'fix the annotation so the cast is unnecessary'),
          ('import-re',
           '\\bimport\\s+re\\b|\\bfrom\\s+re\\s+import\\b',
           '`import re` / `from re import` is a code smell — parse structured data '
           'with its own API instead: JSON -> json.loads, paths -> pathlib.Path, URLs '
           '-> urllib.parse, XML/HTML -> xml.etree.ElementTree / lxml, dates -> '
           'datetime'),
          ('re-call',
           '\\bre\\.(compile|search|match|fullmatch|sub|findall|split)\\s*\\(',
           'Avoid regex for structured data — reach for its parser instead: JSON -> '
           'json.loads, paths -> pathlib.Path, URLs -> urllib.parse, XML/HTML -> '
           'xml.etree.ElementTree / lxml, dates -> datetime'),
          ('string-replace',
           '(?<!\\bos)(?<![Pp]ath)\\.replace\\s*\\(',
           'Avoid .replace() for structured data — edit it through its parser instead '
           '(pathlib.Path for paths, urllib.parse for URLs, json for JSON)'),
          ('string-split',
           '\\.r?split\\s*\\((?!\\s*\\))|\\.r?partition\\s*\\(',
           'Avoid .split(sep)/.rsplit/.partition for structured data — parse it '
           'instead (urllib.parse for URLs, pathlib.Path for paths, json for JSON, '
           'datetime for dates)'),
          ('string-strip',
           '\\.[lr]?strip\\s*\\((?!\\s*\\))',
           'Avoid .strip(chars)/.lstrip/.rstrip for structured data — parse it instead '
           '(urllib.parse for URLs, pathlib.Path for paths, json for JSON, datetime '
           'for dates)'),
          ('bare-except',
           '\\bexcept\\s*:',
           'Bare `except:` catches SystemExit/KeyboardInterrupt — name the exception'),
          ('except-baseexception',
           '\\bexcept\\s+BaseException\\b',
           'except BaseException catches KeyboardInterrupt — use Exception or '
           'narrower'),
          ('suppress',
           '\\bcontextlib\\.suppress\\b',
           'contextlib.suppress silently swallows exceptions — log, handle, or '
           're-raise'),
          ('suppress-import',
           '\\bfrom\\s+contextlib\\s+import\\b.*\\bsuppress\\b',
           'contextlib.suppress silently swallows exceptions — log, handle, or '
           're-raise'),
          ('dataclass',
           '@dataclass|\\bimport\\s+dataclasses\\b|\\bfrom\\s+dataclasses\\s+import\\b',
           'Use Pydantic BaseModel (or TypedDict) instead of dataclasses'),
          ('namedtuple',
           '\\bNamedTuple\\b|\\bnamedtuple\\b',
           'Use Pydantic BaseModel (or TypedDict) instead of NamedTuple/namedtuple'),
          ('subprocess',
           '\\bimport\\s+subprocess\\b|\\bfrom\\s+subprocess\\s+import\\b',
           'Use the `sh` library instead of subprocess'),
          ('os-shell',
           '\\bos\\.(?:system|popen|exec[lv]\\w*)\\s*\\(',
           'Use the `sh` library instead of os.system()/os.popen()/os.exec*()'),
          ('argparse',
           '\\bimport\\s+argparse\\b|\\bfrom\\s+argparse\\s+import\\b',
           'Use `typer` instead of argparse'),
          ('rich-progress',
           '\\brich\\.progress\\b|\\bfrom\\s+rich\\.progress\\s+import\\b',
           'Use `tqdm` instead of rich progress bars'),
          ('os-path', '\\bos\\.path\\b', 'Use pathlib.Path instead of os.path'),
          ('os-file-ops',
           '\\bos\\.(?:getcwd|chdir|listdir|scandir|walk|mkdir|makedirs|rmdir|removedirs|remove|unlink|rename|renames|replace|link|symlink|readlink|stat|lstat|chmod|chown)\\s*\\(',
           'Use pathlib.Path for file/dir operations instead of os.* '
           '(Path.iterdir/mkdir/unlink/rename/replace/stat/...)'),
          ('os-environ',
           '\\bos\\.(?:environ|getenv)\\b',
           'Read configuration through pydantic-settings, not os.environ/os.getenv'),
          ('eval-exec',
           '(?<![.\\w])(?:eval|exec)\\s*\\(',
           'Never use eval()/exec() — parse the data (ast.literal_eval for literals) '
           'or dispatch explicitly'),
          ('utcnow',
           '\\butcnow\\s*\\(',
           'datetime.utcnow() is naive and deprecated — use '
           'datetime.now(timezone.utc)'),
          ('global-statement',
           '^global\\s+\\w',
           'No `global` statements — mutate a module-level holder object or pass state '
           'explicitly'),
          ('private-function',
           '\\bdef\\s+_[a-zA-Z]',
           'No `_` prefix on functions/methods — nothing is private (nest inside '
           'caller if needed)'),
          ('private-class',
           '\\bclass\\s+_[A-Z]',
           'No `_` prefix on classes — nothing is private'),
          ('private-variable',
           '^_[a-zA-Z]\\w*\\s*(?::[^=]*)?=(?!=)(?!.*,\\s*$)',
           'No `_` prefix on variables/constants — nothing is private (unused `_` '
           'function parameters are exempt)')],
 '.svelte': [('as-any',
              '\\bas\\s+any\\b',
              'Never use `as any` — use proper types or type guards'),
             ('as-unknown',
              '\\bas\\s+unknown\\b',
              'Never use `as unknown` — use type guards or proper types'),
             ('any-annotation',
              ':\\s*any\\b',
              'Never use `any` type annotation — use specific types, generics, or '
              '`unknown`'),
             ('any-assertion',
              '<any>',
              'Never use `<any>` type assertion — use proper types'),
             ('ts-ignore',
              '@ts-ignore',
              'Never use @ts-ignore — fix the type error properly'),
             ('ts-expect-error',
              '@ts-expect-error',
              'Never use @ts-expect-error — fix the type error properly'),
             ('ts-nocheck',
              '@ts-nocheck',
              'Never use @ts-nocheck — fix the type errors in the file'),
             ('eslint-disable',
              '//\\s*eslint-disable',
              'Never use eslint-disable — fix the lint issue properly'),
             ('eslint-disable-block',
              '/\\*\\s*eslint-disable',
              'Never use eslint-disable — fix the lint issue properly'),
             ('tslint-disable',
              '//\\s*tslint:disable',
              'Never use tslint:disable — migrate to eslint and fix the issue'),
             ('non-null-assertion',
              '[\\w\\)\\]]!\\.',
              'Postfix `!.` non-null assertion hides a possible null/undefined — '
              'narrow the type or handle the missing case'),
             ('var-declaration',
              '\\bvar\\s+[A-Za-z_$]',
              'Use `const` or `let` instead of `var` — var is function-scoped and '
              'hoisted'),
             ('function-object-type',
              ':\\s*(?:Function|Object)\\b',
              'Never use `Function` or `Object` as a type — declare the call signature '
              'or the object shape'),
             ('console-log',
              '\\bconsole\\.log\\s*\\(',
              'console.log is a debug leftover — remove it or route through a logger')],
 '.ts': [('as-any',
          '\\bas\\s+any\\b',
          'Never use `as any` — use proper types or type guards'),
         ('as-unknown',
          '\\bas\\s+unknown\\b',
          'Never use `as unknown` — use type guards or proper types'),
         ('any-annotation',
          ':\\s*any\\b',
          'Never use `any` type annotation — use specific types, generics, or '
          '`unknown`'),
         ('any-assertion',
          '<any>',
          'Never use `<any>` type assertion — use proper types'),
         ('ts-ignore',
          '@ts-ignore',
          'Never use @ts-ignore — fix the type error properly'),
         ('ts-expect-error',
          '@ts-expect-error',
          'Never use @ts-expect-error — fix the type error properly'),
         ('ts-nocheck',
          '@ts-nocheck',
          'Never use @ts-nocheck — fix the type errors in the file'),
         ('eslint-disable',
          '//\\s*eslint-disable',
          'Never use eslint-disable — fix the lint issue properly'),
         ('eslint-disable-block',
          '/\\*\\s*eslint-disable',
          'Never use eslint-disable — fix the lint issue properly'),
         ('tslint-disable',
          '//\\s*tslint:disable',
          'Never use tslint:disable — migrate to eslint and fix the issue'),
         ('non-null-assertion',
          '[\\w\\)\\]]!\\.',
          'Postfix `!.` non-null assertion hides a possible null/undefined — narrow '
          'the type or handle the missing case'),
         ('var-declaration',
          '\\bvar\\s+[A-Za-z_$]',
          'Use `const` or `let` instead of `var` — var is function-scoped and hoisted'),
         ('function-object-type',
          ':\\s*(?:Function|Object)\\b',
          'Never use `Function` or `Object` as a type — declare the call signature or '
          'the object shape'),
         ('console-log',
          '\\bconsole\\.log\\s*\\(',
          'console.log is a debug leftover — remove it or route through a logger')],
 '.tsx': [('as-any',
           '\\bas\\s+any\\b',
           'Never use `as any` — use proper types or type guards'),
          ('as-unknown',
           '\\bas\\s+unknown\\b',
           'Never use `as unknown` — use type guards or proper types'),
          ('any-annotation',
           ':\\s*any\\b',
           'Never use `any` type annotation — use specific types, generics, or '
           '`unknown`'),
          ('any-assertion',
           '<any>',
           'Never use `<any>` type assertion — use proper types'),
          ('ts-ignore',
           '@ts-ignore',
           'Never use @ts-ignore — fix the type error properly'),
          ('ts-expect-error',
           '@ts-expect-error',
           'Never use @ts-expect-error — fix the type error properly'),
          ('ts-nocheck',
           '@ts-nocheck',
           'Never use @ts-nocheck — fix the type errors in the file'),
          ('eslint-disable',
           '//\\s*eslint-disable',
           'Never use eslint-disable — fix the lint issue properly'),
          ('eslint-disable-block',
           '/\\*\\s*eslint-disable',
           'Never use eslint-disable — fix the lint issue properly'),
          ('tslint-disable',
           '//\\s*tslint:disable',
           'Never use tslint:disable — migrate to eslint and fix the issue'),
          ('non-null-assertion',
           '[\\w\\)\\]]!\\.',
           'Postfix `!.` non-null assertion hides a possible null/undefined — narrow '
           'the type or handle the missing case'),
          ('var-declaration',
           '\\bvar\\s+[A-Za-z_$]',
           'Use `const` or `let` instead of `var` — var is function-scoped and '
           'hoisted'),
          ('function-object-type',
           ':\\s*(?:Function|Object)\\b',
           'Never use `Function` or `Object` as a type — declare the call signature or '
           'the object shape'),
          ('console-log',
           '\\bconsole\\.log\\s*\\(',
           'console.log is a debug leftover — remove it or route through a logger')],
 '.vue': [('as-any',
           '\\bas\\s+any\\b',
           'Never use `as any` — use proper types or type guards'),
          ('as-unknown',
           '\\bas\\s+unknown\\b',
           'Never use `as unknown` — use type guards or proper types'),
          ('any-annotation',
           ':\\s*any\\b',
           'Never use `any` type annotation — use specific types, generics, or '
           '`unknown`'),
          ('any-assertion',
           '<any>',
           'Never use `<any>` type assertion — use proper types'),
          ('ts-ignore',
           '@ts-ignore',
           'Never use @ts-ignore — fix the type error properly'),
          ('ts-expect-error',
           '@ts-expect-error',
           'Never use @ts-expect-error — fix the type error properly'),
          ('ts-nocheck',
           '@ts-nocheck',
           'Never use @ts-nocheck — fix the type errors in the file'),
          ('eslint-disable',
           '//\\s*eslint-disable',
           'Never use eslint-disable — fix the lint issue properly'),
          ('eslint-disable-block',
           '/\\*\\s*eslint-disable',
           'Never use eslint-disable — fix the lint issue properly'),
          ('tslint-disable',
           '//\\s*tslint:disable',
           'Never use tslint:disable — migrate to eslint and fix the issue'),
          ('non-null-assertion',
           '[\\w\\)\\]]!\\.',
           'Postfix `!.` non-null assertion hides a possible null/undefined — narrow '
           'the type or handle the missing case'),
          ('var-declaration',
           '\\bvar\\s+[A-Za-z_$]',
           'Use `const` or `let` instead of `var` — var is function-scoped and '
           'hoisted'),
          ('function-object-type',
           ':\\s*(?:Function|Object)\\b',
           'Never use `Function` or `Object` as a type — declare the call signature or '
           'the object shape'),
          ('console-log',
           '\\bconsole\\.log\\s*\\(',
           'console.log is a debug leftover — remove it or route through a logger')]}

AUTONOMOUS_AGENT_IDENTITIES = ['resolve-editor', 'lup:resolve-editor']

MAXIMUM_ADDED_LINES = 3
